// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "demo/internal/logic/l_chat_login"
	_ "demo/internal/logic/l_chat_message"
)
