// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ChatContent is the golang structure of table chat_content for DAO operations like Where/Data.
type ChatContent struct {
	g.Meta     `orm:"table:chat_content, do:true"`
	Id         interface{} // 聊天信息ID
	Content    interface{} // 聊天内容
	Read       interface{} // 是否已读
	SendId     interface{} // 发送者ID
	ReceiveId  interface{} // 接收者ID
	CreateTime *gtime.Time // 创建时间
	ReadTime   *gtime.Time // 已读时间
}
