// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"demo/internal/model/entity"
	"demo/internal/model/m_chat_content"
	"context"
)

type (
	IChatMessage interface {
		GetMessageById(ctx context.Context, in *string) (out *entity.ChatContent, err error)
		AddMessage(ctx context.Context, in *m_chat_content.AddChatContent) (out *string, err error)
		ReadChatContent(ctx context.Context, in *m_chat_content.ReadChatContent) (out *string, err error)
	}
)

var (
	localChatMessage IChatMessage
)

func ChatMessage() IChatMessage {
	if localChatMessage == nil {
		panic("implement not found for interface IChatMessage, forgot register?")
	}
	return localChatMessage
}

func RegisterChatMessage(i IChatMessage) {
	localChatMessage = i
}
