// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"demo/internal/model/entity"
	"context"
)

type (
	IChatLogin interface {
		SelectByUsername(ctx context.Context, in *string) (out *entity.ChatUser, err error)
		GenerateUserJWT(_ context.Context, in *entity.ChatUser) (out *string, err error)
	}
)

var (
	localChatLogin IChatLogin
)

func ChatLogin() IChatLogin {
	if localChatLogin == nil {
		panic("implement not found for interface IChatLogin, forgot register?")
	}
	return localChatLogin
}

func RegisterChatLogin(i IChatLogin) {
	localChatLogin = i
}
