// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// internalChatContentDao is internal type for wrapping internal DAO implements.
type internalChatContentDao = *internal.ChatContentDao

// chatContentDao is the data access object for table chat_content.
// You can define custom methods on it to extend its functionality as you wish.
type chatContentDao struct {
	internalChatContentDao
}

var (
	// ChatContent is globally public accessible object for table chat_content operations.
	ChatContent = chatContentDao{
		internal.NewChatContentDao(),
	}
)

// Fill with you ideas below.
